Fix typos
Sophanatprime/cus pull request #57
Opened 2024-04-28 16:28 UTC by kianmeng

Found via `codespell -S *.pdf -L te,ist,bu,ot,nd,acn,noo,lod,fo,openin` and `typos --hidden --format brief`

2024-04-29 00:02 UTC, xkwxdyy commented
There is one mistake in your PR: `\inteval` doesn't need to be modified, `\interval` does. Just a simple MWE to check
```latex
\documentclass{article}

\begin{document}

\inteval{1+3}

\end{document}
```
Be careful when you want to change a name of a macro.

2024-04-29 16:45 UTC, kianmeng commented
@xkwxdyy Done. Please check again.

2024-04-29 23:51 UTC, Sophanatprime requested changes

2024-04-29 23:51 UTC, Sophanatprime commented on framedmulticol.sty
This copyright information is copied from [multicol](https://github.com/latex3/latex2e/blob/develop/required/tools/multicol.dtx) , so I prefer to keep it unchanged.

2024-05-01 09:55 UTC, merged

2024-05-01 10:04 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: